apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-eng-apps-prod
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/my-org/data-eng-gitops.git'
        revision: main
        directories:
          - path: eks-data-apps/applications/*
  template:
    metadata:
      name: '{{path.basename}}-prod'
      labels:
        environment: prod
        team: data-eng
    spec:
      project: data-eng-prod
      source:
        repoURL: 'https://github.com/my-org/data-eng-gitops.git'
        targetRevision: main
        path: eks-data-apps/charts/generic-app
        helm:
          valueFiles:
            - ../../../{{path}}/values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: data-eng-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
